### PR TITLE
Add output.jsp and download links for all notes

### LINKED ISSUE #20: Load the output file as a download link

### PR DESCRIPTION
**Pull request by verdantpeas**
### Changes
- Add download link for each note that gets displayed
image

---

- Redirect to output page with download link to session notes
image

--- 

- Write content to docx file: message is the main paragraph notes, title is first element in categories list 
image

---
### Additional information
- Signed url expiry time is set to 7 days (the maximum amount for signed urls) for now, will look into how to make it permanently accessible in another PR or perhaps this is a good opportunity to add user authentication and only display the notes for a single logged in user? What are your thoughts @jtajonera @oulily @joymaneetk 
- Closes #20

### CODE REVIEW

**Comment by verdantpeas** [comment]
Realizing that setting the title of the doc as the first element in categories list may not be the best idea since notes can have multiple categories that are very different. It does feel a little more complete this way though. Does anyone have any strong opinions on this?

**Comment by oulily** [comment]
The first element in the categories list is the one with the highest confidence, so I'm fine with it!

**Comment by oulily** [comment]
Screen Shot 2020-07-21 at 9 30 24 PM

I'm getting an error when I click the link

**Comment by verdantpeas** [comment]
> Screen Shot 2020-07-21 at 9 30 24 PM
> 
> I'm getting an error when I click the link

Hmmm that's strange! Which link are you clicking on (the output page link or the 'view notes' links)? If it is the links from 'view notes', are you testing it with new data? @oulily

**Comment by oulily** [comment]
> > Screen Shot 2020-07-21 at 9 30 24 PM
> > I'm getting an error when I click the link
> 
> Hmmm that's strange! Which link are you clicking on (the output page link or the 'view notes' links)? If it is the links from 'view notes', are you testing it with new data? @oulily

Oh you're right, I was using old data. Nvm it works!

**Review by oulily — APPROVED** [review]
The code looks good to me!

**Pull request merged**
