### PR TITLE
Adds CSS to the web application

### LINKED ISSUE #21: Add CSS

### PR DESCRIPTION
**Pull request by jtajonera**
- Adds Bootstrap and CSS elements to the index.html and output.html page
- Adds an about.html page
- Modifies script.js to accommodate for CSS
Screen Shot 2020-07-20 at 7 09 22 PM
Screen Shot 2020-07-20 at 7 09 30 PM
Screen Shot 2020-07-20 at 7 09 43 PM

### CODE REVIEW

**Comment by oulily** [comment]
Screen Shot 2020-07-20 at 7 46 59 PM

I really like how it looks! Just one small thing: Can you make it so that the bullet points are right next to the category text?

**Comment by jtajonera** [comment]
This is what it looks like now
Screen Shot 2020-07-21 at 2 50 08 AM

**Comment by oulily** [comment]
The bullet points look good! For the blocks of text, can the width of the lines more uniform? Maybe left-aligned?

**Comment by jtajonera** [comment]
@oulily 

I can try making the container bigger so there won't be any random new lines, however the new line characters are generated by OCR as it mimics the format given to it. 

Screen Shot 2020-07-22 at 3 27 39 AM

vs.

Screen Shot 2020-07-22 at 3 25 23 AM

**Comment by verdantpeas** [comment]
> The bullet points look good! For the blocks of text, can the width of the lines more uniform? Maybe left-aligned?

@jtajonera @oulily I think once I merge [this PR](https://github.com/jtajonera/Team-33-Note-App/pull/24#pullrequestreview-453076908) there won't be a need to adjust the message since I removed it and wrote it to the output file instead

**Review by oulily — APPROVED** [review]

**Review by verdantpeas — APPROVED** [review]

**Pull request merged**
